name: CI
on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - name: Set up Python 3.9
        uses: actions/setup-python@v1
        with:
          python-version: 3.9
        
      - name: Install black and pytest
        run: |
          python -m pip install --upgrade pip
          pip install black pytest
      - name: Run black
        run: /
          black --check .
          black .
      - name: Run pytest
        run: /
          pytest
